spring:
  application:
    name: media-playground
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

mediamtx:
  base-url: http://localhost:9997

recording:
  storage:
    recording-dir: storage/recording
    error-dir: storage/error
    completed-dir: storage/completed
